// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Viasoft.Accounting.Infrastructure.EntityFrameworkCore;

namespace Viasoft.Accounting.Infrastructure.Migrations.LegacyAccountingDb
{
    [DbContext(typeof(LegacyAccountingDbContext))]
    [Migration("20201201211751_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Viasoft.Accounting.Domain.Entities.AccountingEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AccountingMonth")
                        .HasColumnName("MESCONT")
                        .HasColumnType("int")
                        .HasMaxLength(4);

                    b.Property<int?>("AccountingYear")
                        .HasColumnName("ANOCONT")
                        .HasColumnType("int")
                        .HasMaxLength(4);

                    b.Property<int>("Code")
                        .HasColumnName("NLANC")
                        .HasColumnType("int")
                        .HasMaxLength(4);

                    b.Property<int>("CompanyCode")
                        .HasColumnName("EMPRESA_RECNO")
                        .HasColumnType("int")
                        .HasMaxLength(4);

                    b.Property<DateTime?>("CreationTimeLegacy")
                        .HasColumnName("DATAHORA")
                        .HasColumnType("datetime2")
                        .HasMaxLength(8);

                    b.Property<string>("Customer")
                        .HasColumnName("CLI")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntryDateLegacy")
                        .HasColumnName("DTLANC")
                        .HasColumnType("nvarchar(8)")
                        .HasMaxLength(8);

                    b.Property<string>("EntryType")
                        .HasColumnName("TIPOLANC")
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.Property<string>("Notes")
                        .HasColumnName("NOTA")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Series")
                        .HasColumnName("SERIE")
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SourceType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CT_CABLANCAMENTOS");
                });

            modelBuilder.Entity("Viasoft.Accounting.Domain.Entities.AccountingEntryHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnName("CODHISTORICO")
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.Property<string>("Description")
                        .HasColumnName("DESCRICAO")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<bool>("IsStatic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Module")
                        .HasColumnType("nvarchar(450)")
                        .HasMaxLength(450);

                    b.HasKey("Id");

                    b.ToTable("CT_HISTPADRAO");
                });

            modelBuilder.Entity("Viasoft.Accounting.Domain.Entities.AccountingEntryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AccountCode")
                        .HasColumnName("COD_CONTA")
                        .HasColumnType("int")
                        .HasMaxLength(4);

                    b.Property<Guid?>("AccountingEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountingOperation")
                        .HasColumnName("CT_OPERACAO")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int>("CompanyCode")
                        .HasColumnName("EMPRESA_RECNO")
                        .HasColumnType("int")
                        .HasMaxLength(4);

                    b.Property<string>("CostCenter")
                        .HasColumnName("CCUSTO")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<decimal?>("CreditValue")
                        .HasColumnName("VALORCREDITO")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DebitValue")
                        .HasColumnName("VALORDEBITO")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EntryCode")
                        .HasColumnName("NLANC")
                        .HasColumnType("int")
                        .HasMaxLength(4);

                    b.Property<string>("EntryHistoricCode")
                        .HasColumnName("CODHISTORICO")
                        .HasColumnType("nvarchar(450)")
                        .HasMaxLength(450);

                    b.Property<string>("Notes")
                        .HasColumnName("OBS")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("CT_LANCAMENTOS");
                });

            modelBuilder.Entity("Viasoft.Accounting.Domain.Entities.AccountingOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cfop")
                        .HasColumnName("CFOP")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Code")
                        .HasColumnName("CODIGO")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("CstCofins")
                        .HasColumnName("CST_COFINS")
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.Property<string>("CstIcms")
                        .HasColumnName("CST_ICMS")
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.Property<string>("CstPis")
                        .HasColumnName("CST_PIS")
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.Property<bool>("CteModule")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Description")
                        .HasColumnName("DESCRICAO")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("DoesntGenerateUnitaryCost")
                        .HasColumnName("NAO_GERA_CUSTO_UNITARIO")
                        .HasColumnType("nvarchar(1)")
                        .HasMaxLength(1);

                    b.Property<string>("EvaluatedSocialContribution")
                        .HasColumnName("EFDPC_COD_CONTRIBU_SOCIAL")
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.Property<string>("ShouldGenerateEntries")
                        .HasColumnName("GERACONTAS")
                        .HasColumnType("nvarchar(1)")
                        .HasMaxLength(1);

                    b.HasKey("Id");

                    b.ToTable("CT_OPERACAO");
                });

            modelBuilder.Entity("Viasoft.Accounting.Domain.Entities.AccountingOperationEntryRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccountingEntryType")
                        .HasColumnType("int");

                    b.Property<Guid>("AccountingOperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookkeepingAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntryVariable")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasMaxLength(450);

                    b.Property<int?>("FirstDisplayInfo")
                        .HasColumnType("int");

                    b.Property<Guid>("HistoricId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("SecondDisplayInfo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AccountingOperationEntryRule");
                });

            modelBuilder.Entity("Viasoft.Accounting.Domain.Entities.BookkeepingAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Classification")
                        .HasColumnName("CLASSIFICACAO")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Code")
                        .HasColumnName("CODIGO")
                        .HasColumnType("int")
                        .HasMaxLength(4);

                    b.Property<string>("IsSynthetic")
                        .HasColumnName("SINTETICO")
                        .HasColumnType("nvarchar(1)")
                        .HasMaxLength(1);

                    b.Property<string>("Name")
                        .HasColumnName("NOME")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("CT_PLANO_CONTAS");
                });

            modelBuilder.Entity("Viasoft.Accounting.Domain.Entities.ManagerialAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnName("PLANO")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Description")
                        .HasColumnName("DESC_PLA")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("PLANO");
                });
#pragma warning restore 612, 618
        }
    }
}
