// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Viasoft.Accounting.Infrastructure.EntityFrameworkCore;

#nullable disable

namespace Viasoft.Accounting.Infrastructure.Migrations.LegacyAccountingDb
{
    [DbContext(typeof(LegacyAccountingDbContext))]
    [Migration("20230630161117_AddIssueInvoiceAccountingOperation")]
    partial class AddIssueInvoiceAccountingOperation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Viasoft.Accounting.Domain.Entities.AccountingEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AccountingMonth")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("MESCONT");

                    b.Property<int?>("AccountingYear")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("ANOCONT");

                    b.Property<int>("Code")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("NLANC");

                    b.Property<int>("CompanyCode")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("EMPRESA_RECNO");

                    b.Property<DateTime?>("CreationTimeLegacy")
                        .HasMaxLength(8)
                        .HasColumnType("datetime2")
                        .HasColumnName("DATAHORA");

                    b.Property<string>("Customer")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CLI");

                    b.Property<string>("Entrada")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ENTRADA");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntryDateLegacy")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("DTLANC");

                    b.Property<string>("EntryType")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("TIPOLANC");

                    b.Property<string>("Fornecedor")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CLIFOR");

                    b.Property<int?>("LegacyIdContaReceber")
                        .HasColumnType("int")
                        .HasColumnName("RECNO_CONTASR");

                    b.Property<string>("Notes")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NOTA");

                    b.Property<string>("Series")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("SERIE");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SourceType")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Usuario")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("USUARIO");

                    b.HasKey("Id");

                    b.ToTable("CT_CABLANCAMENTOS", (string)null);
                });

            modelBuilder.Entity("Viasoft.Accounting.Domain.Entities.AccountingEntryHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("CODHISTORICO");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DESCRICAO");

                    b.Property<bool>("IsStatic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Module")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("CT_HISTPADRAO", (string)null);
                });

            modelBuilder.Entity("Viasoft.Accounting.Domain.Entities.AccountingEntryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AccountCode")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("COD_CONTA");

                    b.Property<Guid?>("AccountingEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountingOperation")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("CT_OPERACAO");

                    b.Property<int>("CompanyCode")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("EMPRESA_RECNO");

                    b.Property<string>("CostCenter")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CCUSTO");

                    b.Property<decimal?>("CreditValue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VALORCREDITO");

                    b.Property<decimal?>("DebitValue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VALORDEBITO");

                    b.Property<int>("EntryCode")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("NLANC");

                    b.Property<string>("EntryHistoricCode")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CODHISTORICO");

                    b.Property<int>("LegacyIdOrigem")
                        .HasColumnType("int")
                        .HasColumnName("CODORIGEM");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("OBS");

                    b.Property<string>("Origem")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ORIGEM");

                    b.Property<string>("Usuario")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("USUARIO");

                    b.HasKey("Id");

                    b.ToTable("CT_LANCAMENTOS", (string)null);
                });

            modelBuilder.Entity("Viasoft.Accounting.Domain.Entities.AccountingOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cfop")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("CFOP");

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("CODIGO");

                    b.Property<string>("CstCofins")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("CST_COFINS");

                    b.Property<string>("CstIcms")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("CST_ICMS");

                    b.Property<string>("CstPis")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("CST_PIS");

                    b.Property<bool>("CteModule")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("DoesntGenerateUnitaryCost")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("NAO_GERA_CUSTO_UNITARIO");

                    b.Property<string>("EvaluatedSocialContribution")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("EFDPC_COD_CONTRIBU_SOCIAL");

                    b.Property<string>("IssueInvoice")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("OPE_FATURAMENTO");

                    b.Property<string>("ShouldGenerateEntries")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("GERACONTAS");

                    b.HasKey("Id");

                    b.ToTable("CT_OPERACAO", (string)null);
                });

            modelBuilder.Entity("Viasoft.Accounting.Domain.Entities.AccountingOperationEntryRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccountingEntryType")
                        .HasColumnType("int");

                    b.Property<Guid>("AccountingOperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookkeepingAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntryVariable")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("FirstDisplayInfo")
                        .HasColumnType("int");

                    b.Property<Guid>("HistoricId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("SecondDisplayInfo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AccountingOperationEntryRule");
                });

            modelBuilder.Entity("Viasoft.Accounting.Domain.Entities.BookkeepingAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Classification")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CLASSIFICACAO");

                    b.Property<int>("Code")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("CODIGO");

                    b.Property<string>("IsSynthetic")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("SINTETICO");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.ToTable("CT_PLANO_CONTAS", (string)null);
                });

            modelBuilder.Entity("Viasoft.Accounting.Domain.Entities.Configuracao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoOperacaoContabilAdiantamento")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("OPE_SINAL_VENDA");

                    b.HasKey("Id");

                    b.ToTable("CT_PARAMETROS", (string)null);
                });

            modelBuilder.Entity("Viasoft.Accounting.Domain.Entities.LegacyComplemento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Campo")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CAMPO");

                    b.Property<int>("Codigo")
                        .HasColumnType("int")
                        .HasColumnName("CODIGO");

                    b.Property<string>("Tabela")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("TABELA");

                    b.HasKey("Id");

                    b.ToTable("CT_VARIAVEL_COMPLE", (string)null);
                });

            modelBuilder.Entity("Viasoft.Accounting.Domain.Entities.LegacyFechamentoPeriodoContabil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Data")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("DATA");

                    b.HasKey("Id");

                    b.ToTable("CT_FECHAMENTO", (string)null);
                });

            modelBuilder.Entity("Viasoft.Accounting.Domain.Entities.LegacyRegraValorLancamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Campo")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CAMPO");

                    b.Property<int>("Codigo")
                        .HasColumnType("int")
                        .HasColumnName("CODIGO");

                    b.HasKey("Id");

                    b.ToTable("CT_VARIAVEL_IMP", (string)null);
                });

            modelBuilder.Entity("Viasoft.Accounting.Domain.Entities.LegacyTemplateLancamentoContabil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CodigoCampo")
                        .HasColumnType("int")
                        .HasColumnName("COD_CAMPO");

                    b.Property<int?>("CodigoComplemento1")
                        .HasColumnType("int")
                        .HasColumnName("COMPL01");

                    b.Property<int?>("CodigoComplemento2")
                        .HasColumnType("int")
                        .HasColumnName("COMPL02");

                    b.Property<int?>("CodigoComplemento3")
                        .HasColumnType("int")
                        .HasColumnName("COMPL03");

                    b.Property<int?>("CodigoComplemento4")
                        .HasColumnType("int")
                        .HasColumnName("COMPL04");

                    b.Property<int?>("CodigoComplemento5")
                        .HasColumnType("int")
                        .HasColumnName("COMPL05");

                    b.Property<int>("CodigoContaContabil")
                        .HasColumnType("int")
                        .HasColumnName("COD_CONTA");

                    b.Property<string>("CodigoHistorico")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CODHISTORICO");

                    b.Property<string>("CodigoOperacaoContabil")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("CODIGO");

                    b.Property<string>("TipoLancamento")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("TIPO");

                    b.HasKey("Id");

                    b.ToTable("CT_OPERACAO_CONTA", (string)null);
                });

            modelBuilder.Entity("Viasoft.Accounting.Domain.Entities.ManagerialAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PLANO");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DESC_PLA");

                    b.HasKey("Id");

                    b.ToTable("PLANO", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
