using System;
using Viasoft.Accounting.Domain.Enums;

namespace Viasoft.Accounting.Domain.Utils;

public static class AccountingEntryItemOriginTypeConversions
{
    public static string GetAccountingEntryItemOriginTypeString(AccountingEntryItemOriginType originType)
    {
        return originType switch
        {
            AccountingEntryItemOriginType.tolDesconhecido => "tolDesconhecido",
            AccountingEntryItemOriginType.tolHistlise => "tolHistlise",
            AccountingEntryItemOriginType.tolHistliseSinal => "tolHistliseSinal",
            AccountingEntryItemOriginType.tolItennota => "tolItennota",
            AccountingEntryItemOriginType.tolNotafisc => "tolNotafisc",
            AccountingEntryItemOriginType.tolNotafiscSinal => "tolNotafiscSinal",
            AccountingEntryItemOriginType.tolFreteConhecimento => "tolFreteConhecimento",
            AccountingEntryItemOriginType.tolCtBens => "tolCtBens",
            AccountingEntryItemOriginType.tolCtDepreciacaoLinearValores => "tolCtDepreciacaoLinearValores",
            AccountingEntryItemOriginType.tolCtDepreciacaoAceleradaValores => "tolCtDepreciacaoAceleradaValores",
            AccountingEntryItemOriginType.tolCtDepreciacaoIncentivadaValores => "tolCtDepreciacaoIncentivadaValores",
            AccountingEntryItemOriginType.tolCtDepreciacaoGerencialValores => "tolCtDepreciacaoGerencialValores",
            AccountingEntryItemOriginType.tolCtMovPatri => "tolCtMovPatri",
            AccountingEntryItemOriginType.tolCtDepreciacaoReavaliacaoLinear => "tolCtDepreciacaoReavaliacaoLinear",
            AccountingEntryItemOriginType.tolCtDepreciacaoReavaliacaoAcelerada => "tolCtDepreciacaoReavaliacaoAcelerada",
            AccountingEntryItemOriginType.tolCtCustoAtribuido => "tolCtCustoAtribuido",
            AccountingEntryItemOriginType.tolCtDepreciacaoCustoAtribuido => "tolCtDepreciacaoCustoAtribuido",
            AccountingEntryItemOriginType.tolCtCreditoAtivo => "tolCtCreditoAtivo",
            AccountingEntryItemOriginType.tolCtCreditoAtivoPis => "tolCtCreditoAtivoPis",
            AccountingEntryItemOriginType.tolCtCreditoAtivoCofins => "tolCtCreditoAtivoCofins",
            AccountingEntryItemOriginType.tolRPA => "tolRPA",
            AccountingEntryItemOriginType.tolApuracaoRPARealizadas => "tolApuracaoRPARealizadas",
            AccountingEntryItemOriginType.tolNFCeItemnota => "tolNFCeItemnota",
            AccountingEntryItemOriginType.tolSATItemnota => "tolSATItemnota",
            AccountingEntryItemOriginType.tolOutrosLancamentos => "tolOutrosLancamentos",
            AccountingEntryItemOriginType.tolCusteioAjusteEntradaEstoque => "tolCusteioAjusteEntradaEstoque",
            AccountingEntryItemOriginType.tolCusteioAjusteSaidaEstoque => "tolCusteioAjusteSaidaEstoque",
            AccountingEntryItemOriginType.tolCusteioInventarioEntradaEstoque => "tolCusteioInventarioEntradaEstoque",
            AccountingEntryItemOriginType.tolCusteioInventarioSaidaEstoque => "tolCusteioInventarioSaidaEstoque",
            AccountingEntryItemOriginType.tolCusteioRequisicaoContraAlmoxarifado => "tolCusteioRequisicaoContraAlmoxarifado",
            AccountingEntryItemOriginType.tolCusteioCustoDasVendasItennota => "tolCusteioCustoDasVendasItennota",
            AccountingEntryItemOriginType.tolCusteioEstornoCustoPorDevolucaoVendaHistlise => "tolCusteioEstornoCustoPorDevolucaoVendaHistlise",
            AccountingEntryItemOriginType.tolCusteioEstornoCustoPorDevolucaoVendaItennota => "tolCusteioEstornoCustoPorDevolucaoVendaItennota",
            AccountingEntryItemOriginType.tolFolhaPontoEBS => "tolFolhaPontoEBS",
            AccountingEntryItemOriginType.tolFolhaPontoSenior => "tolFolhaPontoSenior",
            AccountingEntryItemOriginType.tolFolhaPontoExactusFolhaAdtoSalario => "tolFolhaPontoExactusFolhaAdtoSalario",
            AccountingEntryItemOriginType.tolFolhaPontoExactusProvisaoMensal => "tolFolhaPontoExactusProvisaoMensal",
            AccountingEntryItemOriginType.tolFolhaPontoRhTalent => "tolFolhaPontoRhTalent",
            AccountingEntryItemOriginType.tolFolhaPontoRhTalentManual => "tolFolhaPontoRhTalentManual",
            AccountingEntryItemOriginType.tolFolhaPontoDominio => "tolFolhaPontoDominio",
            AccountingEntryItemOriginType.tolFolhaPontoDominioCentroCusto => "tolFolhaPontoDominioCentroCusto",
            AccountingEntryItemOriginType.tolFolhaPontoSCI => "tolFolhaPontoSCI",
            AccountingEntryItemOriginType.tolFolhaPontoQuestorC => "tolFolhaPontoQuestorC",
            AccountingEntryItemOriginType.tolFolhaPontoQuestorXX => "tolFolhaPontoQuestorXX",
            AccountingEntryItemOriginType.tolZeramento => "tolZeramento",
            AccountingEntryItemOriginType.tolTransferenciaTED => "tolTransferenciaTED",
            AccountingEntryItemOriginType.tolRateioContabil => "tolRateioContabil",
            AccountingEntryItemOriginType.tolInventario => "tolInventario",
            AccountingEntryItemOriginType.tolAjusteEstoque => "tolAjusteEstoque",
            AccountingEntryItemOriginType.tolRequisicaoContraAlmoxarifado => "tolRequisicaoContraAlmoxarifado",
            AccountingEntryItemOriginType.tolRequisicaoContraAlmoxarifadoDevolucao => "tolRequisicaoContraAlmoxarifadoDevolucao",
            AccountingEntryItemOriginType.tolApontamentoProducao => "tolApontamentoProducao",
            AccountingEntryItemOriginType.tolPagamentos => "tolPagamentos",
            AccountingEntryItemOriginType.tolPagamentosAdiantamento => "tolPagamentosAdiantamento",
            AccountingEntryItemOriginType.tolContasAPagar => "tolContasAPagar",
            AccountingEntryItemOriginType.tolContasAPagarAdiantamento => "tolContasAPagarAdiantamento",
            AccountingEntryItemOriginType.tolContasAPagarCompensacao => "tolContasAPagarCompensacao",
            AccountingEntryItemOriginType.tolDescontado => "tolDescontado",
            AccountingEntryItemOriginType.tolContasAReceber => "tolContasAReceber",
            AccountingEntryItemOriginType.tolContasAReceberAdiantamento => "tolContasAReceberAdiantamento",
            AccountingEntryItemOriginType.tolContasAReceberCompensacao => "tolContasAReceberCompensacao",
            AccountingEntryItemOriginType.tolCompensacao => "tolCompensacao",
            AccountingEntryItemOriginType.tolProvisao => "tolProvisao",
            AccountingEntryItemOriginType.tolProvisaoConciliacaoHistliseFor => "tolProvisaoConciliacaoHistliseFor",
            AccountingEntryItemOriginType.tolProvisaoConciliacaoFreteConhecimento => "tolProvisaoConciliacaoFreteConhecimento",
            AccountingEntryItemOriginType.tolSaldoInicial => "tolSaldoInicial",
            AccountingEntryItemOriginType.tolTransferenciaResultado => "tolTransferenciaResultado",
            AccountingEntryItemOriginType.tolCusteioCustosMateriaPrimaHisreal => "tolCusteioCustosMateriaPrimaHisreal",
            AccountingEntryItemOriginType.tolCusteioCustosServicosHistlise => "tolCusteioCustosServicosHistlise",
            AccountingEntryItemOriginType.tolEstornoPagamentoExtratoContasAPagar => "tolEstornoPagamentoExtratoContasAPagar",
            AccountingEntryItemOriginType.tolEstornoPagamentoExtratoContasAReceber => "tolEstornoPagamentoExtratoContasAReceber",
            AccountingEntryItemOriginType.tolCusteioEntradaPAsNoAtivoHisreal => "tolCusteioEntradaPAsNoAtivoHisreal",
            AccountingEntryItemOriginType.tolCusteioEntradaPAsNoAtivoHistlise => "tolCusteioEntradaPAsNoAtivoHistlise",
            AccountingEntryItemOriginType.tolCusteioZeramentoCustosTransferenciaAtivo => "tolCusteioZeramentoCustosTransferenciaAtivo",
            AccountingEntryItemOriginType.tolCusteioOciosidadeFabril => "tolCusteioOciosidadeFabril",
            AccountingEntryItemOriginType.tolCusteioEntradaPAsNoAtivoDiferencaArredondamento => "tolCusteioEntradaPAsNoAtivoDiferencaArredondamento",
            AccountingEntryItemOriginType.tolCteEmissao => "tolCteEmissao",
            AccountingEntryItemOriginType.tolFreteConhecimentoItemRateio => "tolFreteConhecimentoItemRateio",
            AccountingEntryItemOriginType.tolCusteioCustosServicosHistliseParcliseLig => "tolCusteioCustosServicosHistliseParcliseLig",
            AccountingEntryItemOriginType.tolCusteioEntradaPAsNoAtivoHistliseParcliseLig => "tolCusteioEntradaPAsNoAtivoHistliseParcliseLig",
            _ => throw new ArgumentOutOfRangeException(nameof(originType), originType, "Origem não mapeada")
        };
    }

    public static AccountingEntryItemOriginType GetAccountingEntryItemOriginTypeEnum(string originType)
    {
        return originType switch
        {
            "" => AccountingEntryItemOriginType.tolDesconhecido,
            "tolDesconhecido" => AccountingEntryItemOriginType.tolDesconhecido,
            "tolHistlise" => AccountingEntryItemOriginType.tolHistlise,
            "tolHistliseSinal" => AccountingEntryItemOriginType.tolHistliseSinal,
            "tolItennota" => AccountingEntryItemOriginType.tolItennota,
            "tolNotafisc" => AccountingEntryItemOriginType.tolNotafisc,
            "tolNotafiscSinal" => AccountingEntryItemOriginType.tolNotafiscSinal,
            "tolFreteConhecimento" => AccountingEntryItemOriginType.tolFreteConhecimento,
            "tolCtBens" => AccountingEntryItemOriginType.tolCtBens,
            "tolCtDepreciacaoLinearValores" => AccountingEntryItemOriginType.tolCtDepreciacaoLinearValores,
            "tolCtDepreciacaoAceleradaValores" => AccountingEntryItemOriginType.tolCtDepreciacaoAceleradaValores,
            "tolCtDepreciacaoIncentivadaValores" => AccountingEntryItemOriginType.tolCtDepreciacaoIncentivadaValores,
            "tolCtDepreciacaoGerencialValores" => AccountingEntryItemOriginType.tolCtDepreciacaoGerencialValores,
            "tolCtMovPatri" => AccountingEntryItemOriginType.tolCtMovPatri,
            "tolCtDepreciacaoReavaliacaoLinear" => AccountingEntryItemOriginType.tolCtDepreciacaoReavaliacaoLinear,
            "tolCtDepreciacaoReavaliacaoAcelerada" => AccountingEntryItemOriginType.tolCtDepreciacaoReavaliacaoAcelerada,
            "tolCtCustoAtribuido" => AccountingEntryItemOriginType.tolCtCustoAtribuido,
            "tolCtDepreciacaoCustoAtribuido" => AccountingEntryItemOriginType.tolCtDepreciacaoCustoAtribuido,
            "tolCtCreditoAtivo" => AccountingEntryItemOriginType.tolCtCreditoAtivo,
            "tolCtCreditoAtivoPis" => AccountingEntryItemOriginType.tolCtCreditoAtivoPis,
            "tolCtCreditoAtivoCofins" => AccountingEntryItemOriginType.tolCtCreditoAtivoCofins,
            "tolRPA" => AccountingEntryItemOriginType.tolRPA,
            "tolApuracaoRPARealizadas" => AccountingEntryItemOriginType.tolApuracaoRPARealizadas,
            "tolNFCeItemnota" => AccountingEntryItemOriginType.tolNFCeItemnota,
            "tolSATItemnota" => AccountingEntryItemOriginType.tolSATItemnota,
            "tolOutrosLancamentos" => AccountingEntryItemOriginType.tolOutrosLancamentos,
            "tolCusteioAjusteEntradaEstoque" => AccountingEntryItemOriginType.tolCusteioAjusteEntradaEstoque,
            "tolCusteioAjusteSaidaEstoque" => AccountingEntryItemOriginType.tolCusteioAjusteSaidaEstoque,
            "tolCusteioInventarioEntradaEstoque" => AccountingEntryItemOriginType.tolCusteioInventarioEntradaEstoque,
            "tolCusteioInventarioSaidaEstoque" => AccountingEntryItemOriginType.tolCusteioInventarioSaidaEstoque,
            "tolCusteioRequisicaoContraAlmoxarifado" => AccountingEntryItemOriginType.tolCusteioRequisicaoContraAlmoxarifado,
            "tolCusteioCustoDasVendasItennota" => AccountingEntryItemOriginType.tolCusteioCustoDasVendasItennota,
            "tolCusteioEstornoCustoPorDevolucaoVendaHistlise" => AccountingEntryItemOriginType.tolCusteioEstornoCustoPorDevolucaoVendaHistlise,
            "tolCusteioEstornoCustoPorDevolucaoVendaItennota" => AccountingEntryItemOriginType.tolCusteioEstornoCustoPorDevolucaoVendaItennota,
            "tolFolhaPontoEBS" => AccountingEntryItemOriginType.tolFolhaPontoEBS,
            "tolFolhaPontoSenior" => AccountingEntryItemOriginType.tolFolhaPontoSenior,
            "tolFolhaPontoExactusFolhaAdtoSalario" => AccountingEntryItemOriginType.tolFolhaPontoExactusFolhaAdtoSalario,
            "tolFolhaPontoExactusProvisaoMensal" => AccountingEntryItemOriginType.tolFolhaPontoExactusProvisaoMensal,
            "tolFolhaPontoRhTalent" => AccountingEntryItemOriginType.tolFolhaPontoRhTalent,
            "tolFolhaPontoRhTalentManual" => AccountingEntryItemOriginType.tolFolhaPontoRhTalentManual,
            "tolFolhaPontoDominio" => AccountingEntryItemOriginType.tolFolhaPontoDominio,
            "tolFolhaPontoDominioCentroCusto" => AccountingEntryItemOriginType.tolFolhaPontoDominioCentroCusto,
            "tolFolhaPontoSCI" => AccountingEntryItemOriginType.tolFolhaPontoSCI,
            "tolFolhaPontoQuestorC" => AccountingEntryItemOriginType.tolFolhaPontoQuestorC,
            "tolFolhaPontoQuestorXX" => AccountingEntryItemOriginType.tolFolhaPontoQuestorXX,
            "tolZeramento" => AccountingEntryItemOriginType.tolZeramento,
            "tolTransferenciaTED" => AccountingEntryItemOriginType.tolTransferenciaTED,
            "tolRateioContabil" => AccountingEntryItemOriginType.tolRateioContabil,
            "tolInventario" => AccountingEntryItemOriginType.tolInventario,
            "tolAjusteEstoque" => AccountingEntryItemOriginType.tolAjusteEstoque,
            "tolRequisicaoContraAlmoxarifado" => AccountingEntryItemOriginType.tolRequisicaoContraAlmoxarifado,
            "tolRequisicaoContraAlmoxarifadoDevolucao" => AccountingEntryItemOriginType.tolRequisicaoContraAlmoxarifadoDevolucao,
            "tolApontamentoProducao" => AccountingEntryItemOriginType.tolApontamentoProducao,
            "tolPagamentos" => AccountingEntryItemOriginType.tolPagamentos,
            "tolPagamentosAdiantamento" => AccountingEntryItemOriginType.tolPagamentosAdiantamento,
            "tolContasAPagar" => AccountingEntryItemOriginType.tolContasAPagar,
            "tolContasAPagarAdiantamento" => AccountingEntryItemOriginType.tolContasAPagarAdiantamento,
            "tolContasAPagarCompensacao" => AccountingEntryItemOriginType.tolContasAPagarCompensacao,
            "tolDescontado" => AccountingEntryItemOriginType.tolDescontado,
            "tolContasAReceber" => AccountingEntryItemOriginType.tolContasAReceber,
            "tolContasAReceberAdiantamento" => AccountingEntryItemOriginType.tolContasAReceberAdiantamento,
            "tolContasAReceberCompensacao" => AccountingEntryItemOriginType.tolContasAReceberCompensacao,
            "tolCompensacao" => AccountingEntryItemOriginType.tolCompensacao,
            "tolProvisao" => AccountingEntryItemOriginType.tolProvisao,
            "tolProvisaoConciliacaoHistliseFor" => AccountingEntryItemOriginType.tolProvisaoConciliacaoHistliseFor,
            "tolProvisaoConciliacaoFreteConhecimento" => AccountingEntryItemOriginType.tolProvisaoConciliacaoFreteConhecimento,
            "tolSaldoInicial" => AccountingEntryItemOriginType.tolSaldoInicial,
            "tolTransferenciaResultado" => AccountingEntryItemOriginType.tolTransferenciaResultado,
            "tolCusteioCustosMateriaPrimaHisreal" => AccountingEntryItemOriginType.tolCusteioCustosMateriaPrimaHisreal,
            "tolCusteioCustosServicosHistlise" => AccountingEntryItemOriginType.tolCusteioCustosServicosHistlise,
            "tolEstornoPagamentoExtratoContasAPagar" => AccountingEntryItemOriginType.tolEstornoPagamentoExtratoContasAPagar,
            "tolEstornoPagamentoExtratoContasAReceber" => AccountingEntryItemOriginType.tolEstornoPagamentoExtratoContasAReceber,
            "tolCusteioEntradaPAsNoAtivoHisreal" => AccountingEntryItemOriginType.tolCusteioEntradaPAsNoAtivoHisreal,
            "tolCusteioEntradaPAsNoAtivoHistlise" => AccountingEntryItemOriginType.tolCusteioEntradaPAsNoAtivoHistlise,
            "tolCusteioZeramentoCustosTransferenciaAtivo" => AccountingEntryItemOriginType.tolCusteioZeramentoCustosTransferenciaAtivo,
            "tolCusteioOciosidadeFabril" => AccountingEntryItemOriginType.tolCusteioOciosidadeFabril,
            "tolCusteioEntradaPAsNoAtivoDiferencaArredondamento" => AccountingEntryItemOriginType.tolCusteioEntradaPAsNoAtivoDiferencaArredondamento,
            "tolCteEmissao" => AccountingEntryItemOriginType.tolCteEmissao,
            "tolFreteConhecimentoItemRateio" => AccountingEntryItemOriginType.tolFreteConhecimentoItemRateio,
            "tolCusteioCustosServicosHistliseParcliseLig" => AccountingEntryItemOriginType.tolCusteioCustosServicosHistliseParcliseLig,
            "tolCusteioEntradaPAsNoAtivoHistliseParcliseLig" => AccountingEntryItemOriginType.tolCusteioEntradaPAsNoAtivoHistliseParcliseLig,
            _ => throw new ArgumentOutOfRangeException(nameof(originType), originType, "Origem não mapeada")
        };
    }
}