// ReSharper disable InconsistentNaming

namespace Viasoft.Accounting.Domain.Enums
{
    // Se adicionar mais aqui, verifique se existe também no enum do ERP no arquivo Contabilidade.Lancamentos.DetalhesOrigem.DTO.pas
    // Escrita do enum aqui identica a do ERP
    public enum AccountingEntryItemOriginType
    {
        tolDesconhecido = 0,
        tolHistlise = 1,
        tolHistliseSinal = 2,
        tolItennota = 3,
        tolNotafisc = 4,
        tolNotafiscSinal = 5,
        tolFreteConhecimento = 6,
        tolCtBens = 7,
        tolCtDepreciacaoLinearValores = 8,
        tolCtDepreciacaoAceleradaValores = 9,
        tolCtDepreciacaoIncentivadaValores = 10,
        tolCtDepreciacaoGerencialValores = 11,
        tolCtMovPatri = 12,
        tolCtDepreciacaoReavaliacaoLinear = 13,
        tolCtDepreciacaoReavaliacaoAcelerada = 14,
        tolCtCustoAtribuido = 15,
        tolCtDepreciacaoCustoAtribuido = 16,
        tolCtCreditoAtivo = 17,
        tolCtCreditoAtivoPis = 18,
        tolCtCreditoAtivoCofins = 19,
        tolRPA = 20,
        tolApuracaoRPARealizadas = 21,
        tolNFCeItemnota = 22,
        tolSATItemnota = 23,
        tolOutrosLancamentos = 24,
        tolCusteioAjusteEntradaEstoque = 25,
        tolCusteioAjusteSaidaEstoque = 26,
        tolCusteioInventarioEntradaEstoque = 27,
        tolCusteioInventarioSaidaEstoque = 28,
        tolCusteioRequisicaoContraAlmoxarifado = 29,
        tolCusteioCustoDasVendasItennota = 30,
        tolCusteioEstornoCustoPorDevolucaoVendaHistlise = 31,
        tolCusteioEstornoCustoPorDevolucaoVendaItennota = 32,
        tolFolhaPontoEBS = 33,
        tolFolhaPontoSenior = 34,
        tolFolhaPontoExactusFolhaAdtoSalario = 35,
        tolFolhaPontoExactusProvisaoMensal = 36,
        tolFolhaPontoRhTalent = 37,
        tolFolhaPontoRhTalentManual = 38,
        tolFolhaPontoDominio = 39,
        tolFolhaPontoDominioCentroCusto = 40,
        tolFolhaPontoSCI = 41,
        tolFolhaPontoQuestorC = 42,
        tolFolhaPontoQuestorXX = 43,
        tolZeramento = 44,
        tolTransferenciaTED = 45,
        tolRateioContabil = 46,
        tolInventario = 47,
        tolAjusteEstoque = 48,
        tolRequisicaoContraAlmoxarifado = 49,
        tolRequisicaoContraAlmoxarifadoDevolucao = 50,
        tolApontamentoProducao = 51,
        tolPagamentos = 52,
        tolPagamentosAdiantamento = 53,
        tolContasAPagar = 54,
        tolContasAPagarAdiantamento = 55,
        tolContasAPagarCompensacao = 56,
        tolDescontado = 57,
        tolContasAReceber = 58,
        tolContasAReceberAdiantamento = 59,
        tolContasAReceberCompensacao = 60,
        tolCompensacao = 61,
        tolProvisao = 62,
        tolProvisaoConciliacaoHistliseFor = 63,
        tolProvisaoConciliacaoFreteConhecimento = 64,
        tolSaldoInicial = 65,
        tolTransferenciaResultado = 66,
        tolCusteioCustosMateriaPrimaHisreal = 67,
        tolCusteioCustosServicosHistlise = 68,
        tolEstornoPagamentoExtratoContasAPagar = 69,
        tolEstornoPagamentoExtratoContasAReceber = 70,
        tolCusteioEntradaPAsNoAtivoHisreal = 71,
        tolCusteioEntradaPAsNoAtivoHistlise = 72,
        tolCusteioZeramentoCustosTransferenciaAtivo = 73,
        tolCusteioOciosidadeFabril = 74,
        tolCusteioEntradaPAsNoAtivoDiferencaArredondamento = 75,
        tolCteEmissao = 76,
        tolFreteConhecimentoItemRateio = 77,
        tolCusteioCustosServicosHistliseParcliseLig = 78,
        tolCusteioEntradaPAsNoAtivoHistliseParcliseLig = 79
    }
}