export enum TipoValorApuracaoConciliacaoContabil {
    EntradaPagamentoFinanceiro = 1,
    PagamentoFinanceiro = 2,
    EntradaRecebimentoFinanceiro = 3,
    RecebimentoFinanceiro = 4,
    ExtratoFinanceiroPagamento = 5,
    ExtratoFinanceiroRecebimento = 6,
    IcmsCreditarFiscal = 7,
    PisCreditarFiscal = 8,
    CofinsCreditarFiscal = 9,
    IpiCreditarFiscal = 10,
    IcmsRecolherFiscal = 11,
    PisRecolherFiscal = 12,
    CofinsRecolherFiscal = 13,
    IpiRecolherFiscal = 14,
    IcmsStRecolherFiscal = 15,
    IssRecolherFiscal = 16,
    JurosPagamentoFinanceiro = 17,
    MultasPagamentoFinanceiro = 18,
    DescontosObtidosFinanceiro = 19,
    JurosRecebimentoFinanceiro = 20,
    MultasRecebimentoFinanceiro = 21,
    DescontosConcedidosFinanceiro = 22,
    ValorBrutoVendasFaturamento = 23,
    ValorImobilizadosPatrimonial = 24,
    DepreciacaoPatrimonial = 25
}